name: deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy-book:
    runs-on: ubuntu-latest
    steps:
    - name: checkout merge commit
      uses: actions/checkout@v4

    - name: set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: install dependencies
      run: |
        conda install -y python=3.11
        conda env update --file environment.yml --name base
        echo $CONDA/bin >> $GITHUB_PATH

    - name: build the book
      run: |
        jupyter-book build epriprog

    - name: deploy book's HTML to gh-pages branch
      uses: peaceiris/actions-gh-pages@v3.9.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: epriprog/_build/html
